ARG _IMAGE_NAME

FROM ${_IMAGE_NAME} as builder
WORKDIR /src/sum_go
RUN go build -ldflags "-w" sum.go
RUN ls -lh
RUN pwd
RUN which sum

FROM scratch
WORKDIR /app
COPY --from=builder /src/sum_go/sum .
ENTRYPOINT ["./sum"]